// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EquipmentLeaseService.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250120211944_DeleteUnnecessaryRelationsInContractUpdateRequest")]
    partial class DeleteUnnecessaryRelationsInContractUpdateRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EquipmentLeaseService.Core.Domain.Entities.ContractUpdateRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EquipmentQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ProcessEquipmentTypeCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductionFacilityCode")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractUpdateRequests");
                });

            modelBuilder.Entity("EquipmentLeaseService.Core.Domain.Entities.EquipmentPlacementContract", b =>
                {
                    b.Property<Guid>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ContractDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("EquipmentQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ProcessEquipmentTypeCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductionFacilityCode")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ContractId");

                    b.HasIndex("ProcessEquipmentTypeCode");

                    b.HasIndex("ProductionFacilityCode");

                    b.ToTable("EquipmentPlacementContracts");
                });

            modelBuilder.Entity("EquipmentLeaseService.Core.Domain.Entities.ProcessEquipmentType", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("ProcessEquipmentTypes");

                    b.HasData(
                        new
                        {
                            Code = new Guid("be36a363-a19f-492b-83f1-9b18e97539fb"),
                            Area = 120m,
                            Name = "CNC Machine"
                        },
                        new
                        {
                            Code = new Guid("9676ac5e-c7a4-403c-8186-c91422c2cf50"),
                            Area = 80m,
                            Name = "Welding Robot"
                        },
                        new
                        {
                            Code = new Guid("b17f62bf-6073-4df6-862a-65a35bbc81a8"),
                            Area = 150m,
                            Name = "Conveyor Belt"
                        },
                        new
                        {
                            Code = new Guid("352c67e3-5943-42b3-a112-fad57e9f8c0a"),
                            Area = 100m,
                            Name = "Packaging Machine"
                        });
                });

            modelBuilder.Entity("EquipmentLeaseService.Core.Domain.Entities.ProductionFacility", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StandardAreaForEquipment")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Code");

                    b.ToTable("ProductionFacilities");

                    b.HasData(
                        new
                        {
                            Code = new Guid("f10dd7d5-df00-4d0b-a528-e6b477273b21"),
                            Name = "Factory A - Main Building",
                            StandardAreaForEquipment = 1500m
                        },
                        new
                        {
                            Code = new Guid("f5f80771-ab3a-482d-89af-3ee616215539"),
                            Name = "Factory B - Assembly Line",
                            StandardAreaForEquipment = 2500m
                        },
                        new
                        {
                            Code = new Guid("4e0d3341-5af4-4054-91f2-9cf16a719134"),
                            Name = "Factory C - Packaging Area",
                            StandardAreaForEquipment = 1800m
                        });
                });

            modelBuilder.Entity("EquipmentLeaseService.Core.Domain.Entities.ContractUpdateRequest", b =>
                {
                    b.HasOne("EquipmentLeaseService.Core.Domain.Entities.EquipmentPlacementContract", "EquipmentPlacementContract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentPlacementContract");
                });

            modelBuilder.Entity("EquipmentLeaseService.Core.Domain.Entities.EquipmentPlacementContract", b =>
                {
                    b.HasOne("EquipmentLeaseService.Core.Domain.Entities.ProcessEquipmentType", "ProcessEquipmentType")
                        .WithMany("EquipmentPlacementContracts")
                        .HasForeignKey("ProcessEquipmentTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EquipmentLeaseService.Core.Domain.Entities.ProductionFacility", "ProductionFacility")
                        .WithMany("EquipmentPlacementContracts")
                        .HasForeignKey("ProductionFacilityCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcessEquipmentType");

                    b.Navigation("ProductionFacility");
                });

            modelBuilder.Entity("EquipmentLeaseService.Core.Domain.Entities.ProcessEquipmentType", b =>
                {
                    b.Navigation("EquipmentPlacementContracts");
                });

            modelBuilder.Entity("EquipmentLeaseService.Core.Domain.Entities.ProductionFacility", b =>
                {
                    b.Navigation("EquipmentPlacementContracts");
                });
#pragma warning restore 612, 618
        }
    }
}
